#!/bin/bash
read -p 'Dominio: ' dom

unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
sudo ucf --purge /boot/grub/menu.lst
#testa
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade

sudo apt install git unzip nginx certbot libssl-dev swig python3-pip build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less default-jre git python3-setuptools python3-uno python3-lxml unoconv m2crypto libreoffice libreoffice-script-provider-python python3-pip curl software-properties-common -y

sudo useradd -m -d /opt/odoo -U -r -s /bin/bash odoo

sudo apt install postgresql -y

sudo su - postgres -c "createuser -s odoo"

sudo git clone https://github.com/gstota/confs.git /opt/confs

wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb


sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f -y
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
rm wkhtmltox_0.12.1.3-1~bionic_amd64.deb

sudo pip3 install jsonrpc2 daemonize

sudo git clone https://github.com/aeroo/aeroo_docs.git /opt/aeroo/aeroo_docs/
yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf

sudo dd if=/dev/zero of=/swapfile bs=1024 count=500000
sudo chmod 0600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

sudo -iu odoo git clone https://www.github.com/odoo/odoo --depth 1 --branch 11.0 /opt/odoo/odoo11

sudo -iu odoo mkdir /opt/odoo/odoo11-custom-addons

sudo -iu odoo git clone https://github.com/ingadhoc/odoo-argentina.git --branch 11.0 /opt/odoo/odoo11-custom-addons/odoo-argentina-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/account-financial-tools.git --branch 11.0 /opt/odoo/odoo11-custom-addons/account-financial-tools-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/account-payment.git --branch 11.0 /opt/odoo/odoo11-custom-addons/account-payment-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/aeroo_reports.git --branch 11.0 /opt/odoo/odoo11-custom-addons/aeroo_reports-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/argentina-reporting.git --branch 11.0 /opt/odoo/odoo11-custom-addons/argentina-reporting-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/argentina-sale.git --branch 11.0 /opt/odoo/odoo11-custom-addons/argentina-sale-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/miscellaneous.git --branch 11.0 /opt/odoo/odoo11-custom-addons/miscellaneous-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/reporting-engine.git --branch 11.0 /opt/odoo/odoo11-custom-addons/reporting-engine-11.0/
sudo -iu odoo git clone https://github.com/ingadhoc/stock.git --branch 11.0 /opt/odoo/odoo11-custom-addons/stock-11.0/
sudo -iu odoo wget https://apps.odoo.com/loempia/download/partner_identification/11.0.1.0.0/4gXzqj52wzlBc64roBAw7v.zip -O /opt/odoo/odoo11-custom-addons/partner_identification.zip;
#sudo -iu odoo wget https://github.com/ingadhoc/odoo-argentina/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-odoo-argentina.zip
#sudo -iu odoo wget https://github.com/ingadhoc/account-financial-tools/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-account-financial-tools.zip
#sudo -iu odoo wget https://github.com/ingadhoc/account-payment/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-account-payment.zip
#sudo -iu odoo wget https://github.com/ingadhoc/aeroo_reports/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-aeroo_reports.zip
#sudo -iu odoo wget https://github.com/ingadhoc/miscellaneous/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-miscellaneous.zip
#sudo -iu odoo wget https://github.com/ingadhoc/argentina-reporting/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-reporting.zip
#sudo -iu odoo wget https://github.com/ingadhoc/reporting-engine/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-reporting-engine.zip
#sudo -iu odoo wget https://github.com/ingadhoc/argentina-sale/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-sale.zip
#sudo -iu odoo wget https://github.com/ingadhoc/stock/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-stock.zip


#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-odoo-argentina.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-account-financial-tools.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-account-payment.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-aeroo_reports.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-miscellaneous.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-reporting.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-reporting-engine.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-sale.zip -d /opt/odoo/odoo11-custom-addons/
#sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-stock.zip -d /opt/odoo/odoo11-custom-addons/
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/partner_identification.zip -d /opt/odoo/odoo11-custom-addons/

sudo -iu odoo rm /opt/odoo/odoo11-custom-addons/*.zip

sudo -iu odoo pip3 install wheel
sudo -iu odoo pip3 install --user -r /opt/odoo/odoo11-custom-addons/odoo-argentina-11.0/requirements.txt
sudo -iu odoo pip3 install -r /opt/odoo/odoo11-custom-addons/aeroo_reports-11.0/requirements.txt

sudo -iu odoo pip3 install -r /opt/odoo/odoo11/requirements.txt

sudo mv /opt/confs/odoo11.service /etc/systemd/system/
sudo mv /opt/confs/odoo11.conf /etc/
sudo mv /opt/confs/aeroo.service /etc/systemd/system/
sudo mv /opt/confs/office.service /etc/systemd/system/
sudo mv /opt/confs/nginxdef /etc/nginx/sites-available/
sudo mv /opt/confs/letsencrypt.conf /etc/nginx/snippets/
sudo mv /opt/confs/ssl.conf /etc/nginx/snippets/ssl.conf
sudo mv /opt/confs/certbot /etc/cron.d/certbot
sudo systemctl daemon-reload
sudo systemctl enable office.service
sudo systemctl enable aeroo.service
sudo systemctl enable odoo11.service

sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
sudo mkdir -p /var/lib/letsencrypt/.well-known
sudo chgrp www-data /var/lib/letsencrypt
sudo chmod g+s /var/lib/letsencrypt


sudo sed -i -e "s/example.com/$dom/g" /etc/nginx/sites-available/nginxdef
sudo sed -i -e "s/example.com/$dom/g" /opt/confs/odoositedomain
sudo mv /etc/nginx/sites-available/nginxdef /etc/nginx/sites-available/$dom
sudo ln -s /etc/nginx/sites-available/$dom /etc/nginx/sites-enabled
sudo systemctl restart nginx
sudo certbot certonly --agree-tos --email gstota@gmail.com --no-eff-email --webroot -w /var/lib/letsencrypt/ -d $dom -d www.$dom

sudo mv /opt/confs/odoositedomain /etc/nginx/sites-available/$dom
sudo rm -r /opt/confs
sudo reboot

#sudo reboot
