#!/bin/bash

unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
sudo ucf --purge /boot/grub/menu.lst

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade

sudo apt install git unzip libssl-dev swig python3-pip build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less default-jre git python3-setuptools python3-uno python3-lxml unoconv m2crypto libreoffice libreoffice-script-provider-python python3-pip curl software-properties-common -y

sudo useradd -m -d /opt/odoo -U -r -s /bin/bash odoo

sudo apt install postgresql -y

sudo su - postgres -c "createuser -s odoo"

wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb

sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f -y
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin


pip3 install jsonrpc2 daemonize

sudo mkdir /opt/aeroo
cd /opt/aeroo
sudo git clone https://github.com/aeroo/aeroo_docs.git
yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf

cd $home/install
sudo mv /script2 /opt/odoo/
sudo chown -R odoo:odoo /opt/odoo/*
sudo dd if=/dev/zero of=/swapfile bs=1024 count=500000
sudo chmod 0600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

git clone https://www.github.com/odoo/odoo --depth 1 --branch 11.0 /opt/odoo/odoo11

cd /opt/odoo

mkdir /opt/odoo/odoo11-custom-addons
cd odoo11-custom-addons

wget https://github.com/ingadhoc/odoo-argentina/archive/11.0.zip -O ingadhoc-odoo-argentina.zip
wget https://github.com/ingadhoc/account-financial-tools/archive/11.0.zip -O ingadhoc-account-financial-tools.zip
wget https://github.com/ingadhoc/account-payment/archive/11.0.zip -O ingadhoc-account-payment.zip
wget https://github.com/ingadhoc/aeroo_reports/archive/11.0.zip -O ingadhoc-aeroo_reports.zip
wget https://github.com/ingadhoc/miscellaneous/archive/11.0.zip -O ingadhoc-miscellaneous.zip
wget https://github.com/ingadhoc/argentina-reporting/archive/11.0.zip -O ingadhoc-argentina-reporting.zip
wget https://github.com/ingadhoc/reporting-engine/archive/11.0.zip -O ingadhoc-reporting-engine.zip
wget https://github.com/ingadhoc/argentina-sale/archive/11.0.zip -O ingadhoc-argentina-sale.zip
wget https://github.com/ingadhoc/stock/archive/11.0.zip -O ingadhoc-stock.zip
wget https://apps.odoo.com/loempia/download/partner_identification/11.0.1.0.0/4gXzqj52wzlBc64roBAw7v.zip -O partner_identification.zip;

unzip ingadhoc-odoo-argentina.zip
unzip ingadhoc-account-financial-tools.zip
unzip ingadhoc-account-payment.zip
unzip ingadhoc-aeroo_reports.zip
unzip ingadhoc-miscellaneous.zip
unzip ingadhoc-argentina-reporting.zip
unzip ingadhoc-reporting-engine.zip
unzip ingadhoc-argentina-sale.zip
unzip ingadhoc-stock.zip
unzip partner_identification.zip

rm *.zip

pip3 install wheel
pip3 install --user  -r odoo-argentina-11.0/requirements.txt
pip3 install -r aeroo_reports-11.0/requirements.txt

pip3 install -r /opt/odoo/odoo11/requirements.txt
