#!/bin/bash

unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
sudo ucf --purge /boot/grub/menu.lst

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade

sudo apt install git unzip libssl-dev swig python3-pip build-essential wget python3-dev python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less default-jre git python3-setuptools python3-uno python3-lxml unoconv m2crypto libreoffice libreoffice-script-provider-python python3-pip curl software-properties-common -y

sudo useradd -m -d /opt/odoo -U -r -s /bin/bash odoo

sudo apt install postgresql -y

sudo su - postgres -c "createuser -s odoo"

sudo git clone https://github.com/gstota/confs.git /opt/confs

wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.de


sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f -y
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin


pip3 install jsonrpc2 daemonize

sudo git clone https://github.com/aeroo/aeroo_docs.git /opt/aeroo/aeroo_docs/
yes | sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf

sudo dd if=/dev/zero of=/swapfile bs=1024 count=500000
sudo chmod 0600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

sudo -iu odoo git clone https://www.github.com/odoo/odoo --depth 1 --branch 11.0 /opt/odoo/odoo11

sudo -iu odoo mkdir /opt/odoo/odoo11-custom-addons

sudo -iu odoo wget https://github.com/ingadhoc/odoo-argentina/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-odoo-argentina.zip
sudo -iu odoo wget https://github.com/ingadhoc/account-financial-tools/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-account-financial-tools.zip
sudo -iu odoo wget https://github.com/ingadhoc/account-payment/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-account-payment.zip
sudo -iu odoo wget https://github.com/ingadhoc/aeroo_reports/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-aeroo_reports.zip
sudo -iu odoo wget https://github.com/ingadhoc/miscellaneous/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-miscellaneous.zip
sudo -iu odoo wget https://github.com/ingadhoc/argentina-reporting/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-argentina-reporting.zip
sudo -iu odoo wget https://github.com/ingadhoc/reporting-engine/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons//opt/odoo/odoo11-custom-addons/ingadhoc-reporting-engine.zip
sudo -iu odoo wget https://github.com/ingadhoc/argentina-sale/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-sale.zip
sudo -iu odoo wget https://github.com/ingadhoc/stock/archive/11.0.zip -O /opt/odoo/odoo11-custom-addons/ingadhoc-stock.zip
sudo -iu odoo wget https://apps.odoo.com/loempia/download/partner_identification/11.0.1.0.0/4gXzqj52wzlBc64roBAw7v.zip -O /opt/odoo/odoo11-custom-addons/partner_identification.zip;

sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-odoo-argentina.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-account-financial-tools.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-account-payment.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-aeroo_reports.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-miscellaneous.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-reporting.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-reporting-engine.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-argentina-sale.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/ingadhoc-stock.zip
sudo -iu odoo unzip /opt/odoo/odoo11-custom-addons/partner_identification.zip

sudo -iu odoo rm /opt/odoo/odoo11-custom-addons/*.zip

sudo -iu odoo pip3 install wheel
sudo -iu odoo pip3 install --user -r /opt/odoo/odoo11-custom-addons/odoo-argentina-11.0/requirements.txt
sudo -iu odoo pip3 install -r /opt/odoo/odoo11-custom-addons/aeroo_reports-11.0/requirements.txt

sudo -iu odoo pip3 install -r /opt/odoo/odoo11/requirements.txt

sudo mv /opt/confs/odoo11.service /etc/systemd/system/
sudo mv /opt/confs/odoo11.conf /etc/
sudo mv /opt/confs/aeroo.service /etc/systemd/system/
sudo mv /opt/confs/office.service /etc/systemd/system/
sudo rm -r /opt/confs
sudo systemctl daemon-reload
sudo systemctl enable office.service
sudo systemctl enable aeroo.service
sudo systemctl enable odoo11.service

#sudo reboot
