#!/bin/bash


read -p 'Dominio: ' dom

unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
sudo ucf --purge /boot/grub/menu.lst
#testa
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade
sudo apt install git unzip nginx certbot -y

sudo git clone https://github.com/gstota/confs.git /opt/confs
sudo mv /opt/confs/nginxdef /etc/nginx/sites-available/
sudo mv /opt/confs/letsencrypt.conf /etc/nginx/snippets/
sudo mv /opt/confs/ssl.conf /etc/nginx/snippets/ssl.conf
sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
sudo mkdir -p /var/lib/letsencrypt/.well-known
sudo chgrp www-data /var/lib/letsencrypt
sudo chmod g+s /var/lib/letsencrypt


sudo sed -i -e "s/example.com/$dom/g" /etc/nginx/sites-available/nginxdef
sudo sed -i -e "s/example.com/$dom/g" /opt/confs/odoosite
sudo mv /etc/nginx/sites-available/nginxdef /etc/nginx/sites-available/$dom
sudo ln -s /etc/nginx/sites-available/$dom /etc/nginx/sites-enabled/

sudo systemctl restart nginx

sudo certbot certonly --agree-tos --email gstota@gmail.com --no-eff-email --webroot -w /var/lib/letsencrypt/ -d $dom

sudo mv /opt/confs/odoosite /etc/nginx/sites-available/$dom

sudo systemctl restart nginx
